# Site settings
title: Eugene Maslenkov
email: yujiriwc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey everyone! Nice to meet you in my blog. I'm going to write short
  posts about things in programming and in job which looks interested for me.
  Happy reading
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maslenkov.github.io" # the base hostname & protocol for your site
twitter_username: maslenkov_v
github_username:  maslenkov

# Build settings
markdown: kramdown
